# version: "3.7"

# networks:
#   app-connect:
#     driver: bridge

# services:
#   client:
#     build: ./client
#     environment:
#       - PORT=4999
#     ports:
#       - "8082:4999"

#   server:
#     build: ./server
#     environment: 
#       - PORT=5000
#     volumes:
#       - ./server:/server
#       - /server/node
#     ports:
#       - "8081:5000"
#     depends_on:
#       - db
#     networks:
#       - app-connect
#   db:
#     image: mongo
#     container_name: db
#     ports:
#       - "27017:27017"
#     networks:
#       - app-connect


networks:
  app-connect:
    driver: bridge

version: "3.7"
services:
  client:
    build: ./client
    ports:
      - "4999:4999"
    networks:
      - app-connect
  server:
    build: ./server
    environment: 
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-connect
    depends_on: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-connect